//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic_Drygval_Pokhilov_3.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalDisease
    {
        public int idAnimalDisease { get; set; }
        public int idAnimal { get; set; }
        public int idDisease { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Disease Disease { get; set; }
    }
}
