//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic_Drygval_Pokhilov_3.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int idTask { get; set; }
        public System.DateTime DateTask { get; set; }
        public int idStaff { get; set; }
        public int idClient { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
